[package]
name = "ope11-direct-rsx-generated"
version = "0.0.0"
edition = "2021"
publish = false

[features]
default = ["web"]
web = ["dioxus/web"]

[dependencies]
dioxus = { version = "=0.7.10", default-features = false, features = ["minimal", "document"] }
ope11_dioxus_web_features = { package = "web-sys", version = "=0.3.104", features = ["Location", "Window"] }
